"use strict";

let userDatils = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates suscipit
repellendus modi dolor neque, culpa doloribus inventore tenetur temporibus
assumenda id reprehenderit autem facere magnam aliquid! Obcaecati blanditiis at
doloribus rem voluptatem unde itaque repellendus dicta quam, quaerat et
laboriosam veniam nihil ullam, quos alias. Aliquam asperiores natus rem ea
`;

console.log(userDatils.toUpperCase());

let userDatils2 = `LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. 
    VOLUPTATES SUSCIPIT
    REPELLENDUS MODI DOLOR NEQUE, CULPA DOLORIBUS INVENTORE TENETUR TEMPORIBUS
    ASSUMENDA ID REPREHENDERIT AUTEM FACERE MAGNAM ALIQUID! OBCAECATI BLANDITIIS AT
    DOLORIBUS REM VOLUPTATEM UNDE ITAQUE REPELLENDUS DICTA QUAM, QUAERAT ET
    LABORIOSAM VENIAM NIHIL ULLAM, QUOS ALIAS. ALIQUAM ASPERIORES NATUS REM EA`;

console.log(userDatils2.toLowerCase());

let userIdentity = `LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. 
    VOLUPTATES SUSCIPIT
    REPELLENDUS MODI DOLOR NEQUE, CULPA DOLORIBUS INVENTORE TENETUR TEMPORIBUS
    ASSUMENDA ID REPREHENDERIT AUTEM FACERE MAGNAM ALIQUID! OBCAECATI BLANDITIIS AT
    DOLORIBUS REM VOLUPTATEM UNDE ITAQUE REPELLENDUS DICTA QUAM, QUAERAT ET
    LABORIOSAM VENIAM NIHIL ULLAM, QUOS ALIAS. ALIQUAM ASPERIORES NATUS REM EA`;
console.log(userIdentity.toUpperCase());

let historyOfBangladesh = `LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. 
    VOLUPTATES SUSCIPIT
    REPELLENDUS MODI DOLOR NEQUE, CULPA DOLORIBUS INVENTORE TENETUR TEMPORIBUS
    ASSUMENDA ID REPREHENDERIT AUTEM FACERE MAGNAM ALIQUID! OBCAECATI BLANDITIIS AT
    DOLORIBUS REM VOLUPTATEM UNDE ITAQUE REPELLENDUS DICTA QUAM, QUAERAT ET
    LABORIOSAM VENIAM NIHIL ULLAM, QUOS ALIAS. ALIQUAM ASPERIORES NATUS REM EA`;
console.log(historyOfBangladesh.toLowerCase());
